-- viteordre PER-MERCHANT database (one database file per merchant, synced to Turso Cloud).
-- There is no merchant_id column here: the database itself is the tenant boundary.
-- The one exception is merchant_profile, which records which merchant this file belongs to
-- so a restored or copied file can be verified before it is served.
--
-- Conventions: ids are UUIDv7 as TEXT generated by the app, money is INTEGER in minor units
-- of the merchant currency (VND has exponent 0, USD has exponent 2), timestamps are unix
-- seconds INTEGER, booleans are INTEGER 0 or 1, every table is STRICT.
-- Requires PRAGMA foreign_keys = ON on every connection.
-- User ids refer to Better Auth users in the control-plane database, so they are plain TEXT
-- here with no FK.

-- Exactly one row. Business settings for this merchant.
--   tax_rate_bp / service_charge_bp : basis points, 800 means 8 percent
--   prices_include_tax              : 1 when menu prices already contain tax
CREATE TABLE merchant_profile (
    id                 INTEGER PRIMARY KEY CHECK (id = 1),
    merchant_id        TEXT NOT NULL,
    name               TEXT NOT NULL,
    logo_url           TEXT,
    currency           TEXT NOT NULL DEFAULT 'VND',
    timezone           TEXT NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    tax_rate_bp        INTEGER NOT NULL DEFAULT 0 CHECK (tax_rate_bp BETWEEN 0 AND 10000),
    prices_include_tax INTEGER NOT NULL DEFAULT 1 CHECK (prices_include_tax IN (0, 1)),
    service_charge_bp  INTEGER NOT NULL DEFAULT 0 CHECK (service_charge_bp BETWEEN 0 AND 10000),
    receipt_footer     TEXT,
    created_at         INTEGER NOT NULL,
    updated_at         INTEGER NOT NULL
) STRICT;

-- Called agencies in the product spec.
CREATE TABLE branches (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    address    TEXT,
    phone      TEXT,
    timezone   TEXT NOT NULL,
    open_hours TEXT,
    is_active  INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
) STRICT;

-- Restricts a member to specific branches. No rows for a user means all branches.
-- Membership and role live in the control-plane database.
CREATE TABLE member_branch_scopes (
    user_id    TEXT NOT NULL,
    branch_id  TEXT NOT NULL REFERENCES branches (id) ON DELETE CASCADE,
    created_at INTEGER NOT NULL,
    PRIMARY KEY (user_id, branch_id)
) STRICT;
CREATE INDEX idx_branch_scopes_branch ON member_branch_scopes (branch_id);

-- Bank accounts used to build payment QR codes. branch_id NULL means a merchant-wide account.
-- default_scope is the uniqueness guard for the default account: set it to the branch id,
-- or to the text merchant for a merchant-wide default, and leave it NULL otherwise.
-- Because NULLs are distinct in UNIQUE, there can be at most one default per scope.
CREATE TABLE bank_accounts (
    id             TEXT PRIMARY KEY,
    branch_id      TEXT REFERENCES branches (id) ON DELETE CASCADE,
    bank_bin       TEXT NOT NULL,
    bank_name      TEXT,
    account_number TEXT NOT NULL,
    account_name   TEXT NOT NULL,
    default_scope  TEXT UNIQUE,
    is_active      INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at     INTEGER NOT NULL,
    updated_at     INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_bank_accounts_branch ON bank_accounts (branch_id);

-- Payment provider settings, configured by the merchant owner.
--   api_key_hash : SHA-256 hex of the API key SePay sends in the Authorization header.
--                  The plaintext is never stored, we only compare hashes.
--   code_prefix  : the payment-code prefix configured on the SePay side. SePay extracts a
--                  code with this prefix from the transfer memo and sends it as code.
CREATE TABLE payment_integrations (
    id              TEXT PRIMARY KEY,
    provider        TEXT NOT NULL UNIQUE CHECK (provider IN ('sepay')),
    api_key_hash    TEXT,
    code_prefix     TEXT NOT NULL DEFAULT 'VO',
    bank_account_id TEXT REFERENCES bank_accounts (id) ON DELETE SET NULL,
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL
) STRICT;
