-- viteordre CONTROL-PLANE database.
-- Holds everything that must be resolvable BEFORE a merchant database is opened:
-- the merchant registry, where each merchant database lives, who belongs to which
-- merchant, pending invitations (invitees have no account yet) and webhook routing.
-- Better Auth owns its own tables (user, session, account, verification) in this same
-- database. user_id columns below are plain TEXT with no FK on purpose, so migration
-- order never depends on Better Auth.
--
-- Conventions: ids are UUIDv7 as TEXT generated by the app, timestamps are unix seconds
-- INTEGER, every table is STRICT. Requires PRAGMA foreign_keys = ON on every connection.

CREATE TABLE merchants (
    id         TEXT PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'closed')),
    created_by TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
) STRICT;

-- Where and in what state each merchant database is. Also the work list for fan-out
-- migrations: select rows where schema_version is below the latest tenant migration.
CREATE TABLE tenant_databases (
    merchant_id      TEXT PRIMARY KEY REFERENCES merchants (id) ON DELETE CASCADE,
    shard_id         TEXT NOT NULL,
    db_path          TEXT NOT NULL,
    cloud_db_name    TEXT,
    schema_version   INTEGER NOT NULL DEFAULT 0,
    status           TEXT NOT NULL DEFAULT 'provisioning'
                     CHECK (status IN ('provisioning', 'ready', 'migrating', 'failed', 'archived')),
    last_error       TEXT,
    last_migrated_at INTEGER,
    last_synced_at   INTEGER,
    created_at       INTEGER NOT NULL,
    updated_at       INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_tenant_databases_shard ON tenant_databases (shard_id, status);
CREATE INDEX idx_tenant_databases_version ON tenant_databases (schema_version);

CREATE TABLE merchant_members (
    id          TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL REFERENCES merchants (id) ON DELETE CASCADE,
    user_id     TEXT NOT NULL,
    role        TEXT NOT NULL CHECK (role IN ('owner', 'manager', 'staff')),
    created_at  INTEGER NOT NULL,
    UNIQUE (merchant_id, user_id)
) STRICT;
CREATE INDEX idx_members_user ON merchant_members (user_id);

-- Email invitations. email is stored lowercase by the app. branch_ids is a JSON array of
-- branch ids that live in the merchant database, NULL means all branches. On acceptance
-- the app inserts the membership here and the branch scopes into the merchant database.
CREATE TABLE member_invitations (
    id          TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL REFERENCES merchants (id) ON DELETE CASCADE,
    email       TEXT NOT NULL,
    role        TEXT NOT NULL CHECK (role IN ('manager', 'staff')),
    branch_ids  TEXT,
    token_hash  TEXT NOT NULL UNIQUE,
    invited_by  TEXT NOT NULL,
    expires_at  INTEGER NOT NULL,
    accepted_at INTEGER,
    accepted_by TEXT,
    revoked_at  INTEGER,
    created_at  INTEGER NOT NULL
) STRICT;
CREATE INDEX idx_invitations_email ON member_invitations (email);
CREATE INDEX idx_invitations_merchant ON member_invitations (merchant_id, accepted_at);

-- Maps the opaque id in /webhooks/sepay/{id} to a merchant. The SePay API key itself is
-- verified against the hash stored in the merchant database.
CREATE TABLE webhook_endpoints (
    id          TEXT PRIMARY KEY,
    merchant_id TEXT NOT NULL REFERENCES merchants (id) ON DELETE CASCADE,
    provider    TEXT NOT NULL CHECK (provider IN ('sepay')),
    is_active   INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at  INTEGER NOT NULL,
    UNIQUE (merchant_id, provider)
) STRICT;
